<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\DailyWord;
use Illuminate\Support\Carbon;

class DailyWordSeeder extends Seeder
{
    public function run()
    {
        $words = [
            ['english_word' => 'Gather', 'pronunciation' => 'ˈɡæðər', 'hindi_word' => 'इकट्ठा करना', 'hindi_meaning' => 'ikatha karna', 'publish_date' => NULL],
            ['english_word' => 'Whisper', 'pronunciation' => 'ˈwɪspər', 'hindi_word' => 'फुसफुसाना', 'hindi_meaning' => 'phusphusana', 'publish_date' => NULL],
            ['english_word' => 'Stumble', 'pronunciation' => 'ˈstʌmbəl', 'hindi_word' => 'ठोकर खाना', 'hindi_meaning' => 'thokar khana', 'publish_date' => NULL],
            ['english_word' => 'Mend', 'pronunciation' => 'mɛnd', 'hindi_word' => 'सुधारना', 'hindi_meaning' => 'sudharna', 'publish_date' => NULL],
            ['english_word' => 'Drift', 'pronunciation' => 'drɪft', 'hindi_word' => 'बहना', 'hindi_meaning' => 'bahna', 'publish_date' => NULL],
            ['english_word' => 'Glance', 'pronunciation' => 'ɡlɑːns', 'hindi_word' => 'झलक', 'hindi_meaning' => 'jhalak', 'publish_date' => NULL],
            ['english_word' => 'Tremble', 'pronunciation' => 'ˈtrɛmbəl', 'hindi_word' => 'काँपना', 'hindi_meaning' => 'kampna', 'publish_date' => NULL],
            ['english_word' => 'Scatter', 'pronunciation' => 'ˈskætər', 'hindi_word' => 'बिखेरना', 'hindi_meaning' => 'bikherna', 'publish_date' => NULL],
            ['english_word' => 'Pause', 'pronunciation' => 'pɔːz', 'hindi_word' => 'रुकना', 'hindi_meaning' => 'rukna', 'publish_date' => NULL],
            ['english_word' => 'Blend', 'pronunciation' => 'blɛnd', 'hindi_word' => 'मिलाना', 'hindi_meaning' => 'milana', 'publish_date' => NULL],
            ['english_word' => 'Grasp', 'pronunciation' => 'ɡrɑːsp', 'hindi_word' => 'पकड़ना', 'hindi_meaning' => 'pakadna', 'publish_date' => NULL],
            ['english_word' => 'Shiver', 'pronunciation' => 'ˈʃɪvər', 'hindi_word' => 'काँपना', 'hindi_meaning' => 'kampna', 'publish_date' => NULL],
            ['english_word' => 'Clutch', 'pronunciation' => 'klʌtʃ', 'hindi_word' => 'कसकर पकड़ना', 'hindi_meaning' => 'kaskar pakadna', 'publish_date' => NULL],
            ['english_word' => 'Fumble', 'pronunciation' => 'ˈfʌmbəl', 'hindi_word' => 'टटोलना', 'hindi_meaning' => 'tatolna', 'publish_date' => NULL],
            ['english_word' => 'Hover', 'pronunciation' => 'ˈhɒvər', 'hindi_word' => 'मँडराना', 'hindi_meaning' => 'mandrana', 'publish_date' => NULL],
            ['english_word' => 'Crumble', 'pronunciation' => 'ˈkrʌmbəl', 'hindi_word' => 'टूटना', 'hindi_meaning' => 'tootna', 'publish_date' => NULL],
            ['english_word' => 'Dangle', 'pronunciation' => 'ˈdæŋɡəl', 'hindi_word' => 'लटकना', 'hindi_meaning' => 'latkana', 'publish_date' => NULL],
            ['english_word' => 'Sway', 'pronunciation' => 'sweɪ', 'hindi_word' => 'डोलना', 'hindi_meaning' => 'dolna', 'publish_date' => NULL],
            ['english_word' => 'Tug', 'pronunciation' => 'tʌɡ', 'hindi_word' => 'खींचना', 'hindi_meaning' => 'kheenchana', 'publish_date' => NULL],
            ['english_word' => 'Twist', 'pronunciation' => 'twɪst', 'hindi_word' => 'मोड़ना', 'hindi_meaning' => 'modna', 'publish_date' => NULL],
            ['english_word' => 'Glide', 'pronunciation' => 'ɡlaɪd', 'hindi_word' => 'सरकना', 'hindi_meaning' => 'sarakna', 'publish_date' => NULL],
            ['english_word' => 'Creep', 'pronunciation' => 'kriːp', 'hindi_word' => 'रेंगना', 'hindi_meaning' => 'rengna', 'publish_date' => NULL],
            ['english_word' => 'Dash', 'pronunciation' => 'dæʃ', 'hindi_word' => 'दौड़ना', 'hindi_meaning' => 'daudna', 'publish_date' => NULL],
            ['english_word' => 'Leap', 'pronunciation' => 'liːp', 'hindi_word' => 'कूदना', 'hindi_meaning' => 'koodna', 'publish_date' => NULL],
            ['english_word' => 'Stroll', 'pronunciation' => 'strəʊl', 'hindi_word' => 'टहलना', 'hindi_meaning' => 'tahilna', 'publish_date' => NULL],
            ['english_word' => 'Wander', 'pronunciation' => 'ˈwɒndər', 'hindi_word' => 'भटकना', 'hindi_meaning' => 'bhatakna', 'publish_date' => NULL],
            ['english_word' => 'Roam', 'pronunciation' => 'rəʊm', 'hindi_word' => 'घूमना', 'hindi_meaning' => 'ghoomna', 'publish_date' => NULL],
            ['english_word' => 'Chase', 'pronunciation' => 'tʃeɪs', 'hindi_word' => 'पीछा करना', 'hindi_meaning' => 'peechha karna', 'publish_date' => NULL],
            ['english_word' => 'Flee', 'pronunciation' => 'fliː', 'hindi_word' => 'भागना', 'hindi_meaning' => 'bhagna', 'publish_date' => NULL],
            ['english_word' => 'Pursue', 'pronunciation' => 'pəˈsjuː', 'hindi_word' => 'पीछा करना', 'hindi_meaning' => 'peechha karna', 'publish_date' => NULL],
            ['english_word' => 'Retreat', 'pronunciation' => 'rɪˈtriːt', 'hindi_word' => 'पीछे हटना', 'hindi_meaning' => 'peechhe hatna', 'publish_date' => NULL],
            ['english_word' => 'Advance', 'pronunciation' => 'ədˈvɑːns', 'hindi_word' => 'आगे बढ़ना', 'hindi_meaning' => 'aage badhna', 'publish_date' => NULL],
            ['english_word' => 'Halt', 'pronunciation' => 'hɔːlt', 'hindi_word' => 'रुकना', 'hindi_meaning' => 'rukna', 'publish_date' => NULL],
            ['english_word' => 'Rush', 'pronunciation' => 'rʌʃ', 'hindi_word' => 'जल्दी करना', 'hindi_meaning' => 'jaldi karna', 'publish_date' => NULL],
            ['english_word' => 'Delay', 'pronunciation' => 'dɪˈleɪ', 'hindi_word' => 'देरी करना', 'hindi_meaning' => 'deri karna', 'publish_date' => NULL],
            ['english_word' => 'Hasten', 'pronunciation' => 'ˈheɪsən', 'hindi_word' => 'जल्दी करना', 'hindi_meaning' => 'jaldi karna', 'publish_date' => NULL],
            ['english_word' => 'Linger', 'pronunciation' => 'ˈlɪŋɡər', 'hindi_word' => 'रुकना', 'hindi_meaning' => 'rukna', 'publish_date' => NULL],
            ['english_word' => 'Tarry', 'pronunciation' => 'ˈtæri', 'hindi_word' => 'देर करना', 'hindi_meaning' => 'der karna', 'publish_date' => NULL],
            ['english_word' => 'Proceed', 'pronunciation' => 'prəˈsiːd', 'hindi_word' => 'आगे बढ़ना', 'hindi_meaning' => 'aage badhna', 'publish_date' => NULL],
            ['english_word' => 'Depart', 'pronunciation' => 'dɪˈpɑːt', 'hindi_word' => 'प्रस्थान करना', 'hindi_meaning' => 'prasthaan karna', 'publish_date' => NULL],
            ['english_word' => 'Arrive', 'pronunciation' => 'əˈraɪv', 'hindi_word' => 'पहुँचना', 'hindi_meaning' => 'pahunchana', 'publish_date' => NULL],
            ['english_word' => 'Vanish', 'pronunciation' => 'ˈvænɪʃ', 'hindi_word' => 'गायब होना', 'hindi_meaning' => 'gayab hona', 'publish_date' => NULL],
            ['english_word' => 'Appear', 'pronunciation' => 'əˈpɪər', 'hindi_word' => 'प्रकट होना', 'hindi_meaning' => 'prakat hona', 'publish_date' => NULL],
            ['english_word' => 'Fade', 'pronunciation' => 'feɪd', 'hindi_word' => 'मंद पड़ना', 'hindi_meaning' => 'mand padna', 'publish_date' => NULL],
            ['english_word' => 'Brighten', 'pronunciation' => 'ˈbraɪtən', 'hindi_word' => 'चमकना', 'hindi_meaning' => 'chamakna', 'publish_date' => NULL],
            ['english_word' => 'Dim', 'pronunciation' => 'dɪm', 'hindi_word' => 'मंद करना', 'hindi_meaning' => 'mand karna', 'publish_date' => NULL],
            ['english_word' => 'Glow', 'pronunciation' => 'ɡləʊ', 'hindi_word' => 'चमकना', 'hindi_meaning' => 'chamakna', 'publish_date' => NULL],
            ['english_word' => 'Sparkle', 'pronunciation' => 'ˈspɑːkəl', 'hindi_word' => 'चमकना', 'hindi_meaning' => 'chamakna', 'publish_date' => NULL],
            ['english_word' => 'Flicker', 'pronunciation' => 'ˈflɪkər', 'hindi_word' => 'टिमटिमाना', 'hindi_meaning' => 'timtimana', 'publish_date' => NULL],
            ['english_word' => 'Shine', 'pronunciation' => 'ʃaɪn', 'hindi_word' => 'चमकना', 'hindi_meaning' => 'chamakna', 'publish_date' => NULL],
            ['english_word' => 'Dull', 'pronunciation' => 'dʌl', 'hindi_word' => 'फीका करना', 'hindi_meaning' => 'pheeka karna', 'publish_date' => NULL],
            ['english_word' => 'Polish', 'pronunciation' => 'ˈpɒlɪʃ', 'hindi_word' => 'चमकाना', 'hindi_meaning' => 'chamakana', 'publish_date' => NULL],
            ['english_word' => 'Scratch', 'pronunciation' => 'skrætʃ', 'hindi_word' => 'खरोंचना', 'hindi_meaning' => 'kharonchna', 'publish_date' => NULL],
            ['english_word' => 'Scrape', 'pronunciation' => 'skreɪp', 'hindi_word' => 'खुरचना', 'hindi_meaning' => 'khurchna', 'publish_date' => NULL],
            ['english_word' => 'Rub', 'pronunciation' => 'rʌb', 'hindi_word' => 'रगड़ना', 'hindi_meaning' => 'ragadna', 'publish_date' => NULL],
            ['english_word' => 'Wipe', 'pronunciation' => 'waɪp', 'hindi_word' => 'पोंछना', 'hindi_meaning' => 'ponchna', 'publish_date' => NULL],
            ['english_word' => 'Smear', 'pronunciation' => 'smɪər', 'hindi_word' => 'लिपना', 'hindi_meaning' => 'lipna', 'publish_date' => NULL],
            ['english_word' => 'Stain', 'pronunciation' => 'steɪn', 'hindi_word' => 'दाग लगाना', 'hindi_meaning' => 'daag lagana', 'publish_date' => NULL],
            ['english_word' => 'Cleanse', 'pronunciation' => 'klɛnz', 'hindi_word' => 'साफ करना', 'hindi_meaning' => 'saaf karna', 'publish_date' => NULL],
            ['english_word' => 'Rinse', 'pronunciation' => 'rɪns', 'hindi_word' => 'कुल्ला करना', 'hindi_meaning' => 'kulla karna', 'publish_date' => NULL],
            ['english_word' => 'Soak', 'pronunciation' => 'səʊk', 'hindi_word' => 'भिगोना', 'hindi_meaning' => 'bhigona', 'publish_date' => NULL],
            ['english_word' => 'Drain', 'pronunciation' => 'dreɪn', 'hindi_word' => 'निकालना', 'hindi_meaning' => 'nikalna', 'publish_date' => NULL],
            ['english_word' => 'Fill', 'pronunciation' => 'fɪl', 'hindi_word' => 'भरना', 'hindi_meaning' => 'bharna', 'publish_date' => NULL],
            ['english_word' => 'Empty', 'pronunciation' => 'ˈɛmpti', 'hindi_word' => 'खाली करना', 'hindi_meaning' => 'khali karna', 'publish_date' => NULL],
            ['english_word' => 'Pour', 'pronunciation' => 'pɔːr', 'hindi_word' => 'डालना', 'hindi_meaning' => 'dalna', 'publish_date' => NULL],
            ['english_word' => 'Spill', 'pronunciation' => 'spɪl', 'hindi_word' => 'गिराना', 'hindi_meaning' => 'girana', 'publish_date' => NULL],
            ['english_word' => 'Drip', 'pronunciation' => 'drɪp', 'hindi_word' => 'टपकना', 'hindi_meaning' => 'tapakna', 'publish_date' => NULL],
            ['english_word' => 'Splash', 'pronunciation' => 'splæʃ', 'hindi_word' => 'छींटें मारना', 'hindi_meaning' => 'chheenten marna', 'publish_date' => NULL],
            ['english_word' => 'Spray', 'pronunciation' => 'spreɪ', 'hindi_word' => 'छिड़कना', 'hindi_meaning' => 'chhidakna', 'publish_date' => NULL],
            ['english_word' => 'Stir', 'pronunciation' => 'stɜːr', 'hindi_word' => 'हिलाना', 'hindi_meaning' => 'hilana', 'publish_date' => NULL],
            ['english_word' => 'Shake', 'pronunciation' => 'ʃeɪk', 'hindi_word' => 'हिलाना', 'hindi_meaning' => 'hilana', 'publish_date' => NULL],
            ['english_word' => 'Toss', 'pronunciation' => 'tɒs', 'hindi_word' => 'उछालना', 'hindi_meaning' => 'uchhalna', 'publish_date' => NULL],
            ['english_word' => 'Flip', 'pronunciation' => 'flɪp', 'hindi_word' => 'पलटना', 'hindi_meaning' => 'palatna', 'publish_date' => NULL],
            ['english_word' => 'Turn', 'pronunciation' => 'tɜːn', 'hindi_word' => 'मोड़ना', 'hindi_meaning' => 'modna', 'publish_date' => NULL],
            ['english_word' => 'Spin', 'pronunciation' => 'spɪn', 'hindi_word' => 'घुमाना', 'hindi_meaning' => 'ghumana', 'publish_date' => NULL],
            ['english_word' => 'Roll', 'pronunciation' => 'rəʊl', 'hindi_word' => 'लपेटना', 'hindi_meaning' => 'lapetna', 'publish_date' => NULL],
            ['english_word' => 'Fold', 'pronunciation' => 'fəʊld', 'hindi_word' => 'मोड़ना', 'hindi_meaning' => 'modna', 'publish_date' => NULL],
            ['english_word' => 'Unfold', 'pronunciation' => 'ʌnˈfəʊld', 'hindi_word' => 'खोलना', 'hindi_meaning' => 'kholna', 'publish_date' => NULL],
            ['english_word' => 'Crumple', 'pronunciation' => 'ˈkrʌmpəl', 'hindi_word' => 'सिकोड़ना', 'hindi_meaning' => 'sikodna', 'publish_date' => NULL],
            ['english_word' => 'Smooth', 'pronunciation' => 'smuːð', 'hindi_word' => 'चिकना करना', 'hindi_meaning' => 'chikna karna', 'publish_date' => NULL],
            ['english_word' => 'Wrinkle', 'pronunciation' => 'ˈrɪŋkəl', 'hindi_word' => 'झुर्री डालना', 'hindi_meaning' => 'jhurri dalna', 'publish_date' => NULL],
            ['english_word' => 'Stretch', 'pronunciation' => 'strɛtʃ', 'hindi_word' => 'खींचना', 'hindi_meaning' => 'kheenchana', 'publish_date' => NULL],
            ['english_word' => 'Shrink', 'pronunciation' => 'ʃrɪŋk', 'hindi_word' => 'सिकुड़ना', 'hindi_meaning' => 'sikudna', 'publish_date' => NULL],
            ['english_word' => 'Expand', 'pronunciation' => 'ɪkˈspænd', 'hindi_word' => 'फैलाना', 'hindi_meaning' => 'failana', 'publish_date' => NULL],
            ['english_word' => 'Compress', 'pronunciation' => 'kəmˈprɛs', 'hindi_word' => 'दबाना', 'hindi_meaning' => 'dabana', 'publish_date' => NULL],
            ['english_word' => 'Squeeze', 'pronunciation' => 'skwiːz', 'hindi_word' => 'निचोड़ना', 'hindi_meaning' => 'nichodna', 'publish_date' => NULL],
            ['english_word' => 'Release', 'pronunciation' => 'rɪˈliːs', 'hindi_word' => 'छोड़ना', 'hindi_meaning' => 'chhodna', 'publish_date' => NULL],
            ['english_word' => 'Grip', 'pronunciation' => 'ɡrɪp', 'hindi_word' => 'पकड़ना', 'hindi_meaning' => 'pakadna', 'publish_date' => NULL],
            ['english_word' => 'Loosen', 'pronunciation' => 'ˈluːsən', 'hindi_word' => 'ढीला करना', 'hindi_meaning' => 'dhila karna', 'publish_date' => NULL],
            ['english_word' => 'Tighten', 'pronunciation' => 'ˈtaɪtən', 'hindi_word' => 'कसना', 'hindi_meaning' => 'kasna', 'publish_date' => NULL],
            ['english_word' => 'Fasten', 'pronunciation' => 'ˈfɑːsən', 'hindi_word' => 'बाँधना', 'hindi_meaning' => 'bandhna', 'publish_date' => NULL],
            ['english_word' => 'Unfasten', 'pronunciation' => 'ʌnˈfɑːsən', 'hindi_word' => 'खोलना', 'hindi_meaning' => 'kholna', 'publish_date' => NULL],
            ['english_word' => 'Tie', 'pronunciation' => 'taɪ', 'hindi_word' => 'बाँधना', 'hindi_meaning' => 'bandhna', 'publish_date' => NULL],
            ['english_word' => 'Untie', 'pronunciation' => 'ʌnˈtaɪ', 'hindi_word' => 'खोलना', 'hindi_meaning' => 'kholna', 'publish_date' => NULL],
            ['english_word' => 'Knot', 'pronunciation' => 'nɒt', 'hindi_word' => 'गाँठ बाँधना', 'hindi_meaning' => 'ganth bandhna', 'publish_date' => NULL],
            ['english_word' => 'Unknot', 'pronunciation' => 'ʌnˈnɒt', 'hindi_word' => 'गाँठ खोलना', 'hindi_meaning' => 'ganth kholna', 'publish_date' => NULL],
            ['english_word' => 'Thread', 'pronunciation' => 'θrɛd', 'hindi_word' => 'धागा डालना', 'hindi_meaning' => 'dhaga dalna', 'publish_date' => NULL],
            ['english_word' => 'Stitch', 'pronunciation' => 'stɪtʃ', 'hindi_word' => 'सिलाई करना', 'hindi_meaning' => 'silai karna', 'publish_date' => NULL],
            ['english_word' => 'Sew', 'pronunciation' => 'səʊ', 'hindi_word' => 'सिलना', 'hindi_meaning' => 'silna', 'publish_date' => NULL],
            ['english_word' => 'Rip', 'pronunciation' => 'rɪp', 'hindi_word' => 'फाड़ना', 'hindi_meaning' => 'phadna', 'publish_date' => NULL],
            ['english_word' => 'Tear', 'pronunciation' => 'tɛər', 'hindi_word' => 'फाड़ना', 'hindi_meaning' => 'phadna', 'publish_date' => NULL],
            ['english_word' => 'Patch', 'pronunciation' => 'pætʃ', 'hindi_word' => 'पैबंद लगाना', 'hindi_meaning' => 'paiband lagana', 'publish_date' => NULL],
            ['english_word' => 'Darn', 'pronunciation' => 'dɑːn', 'hindi_word' => 'रफू करना', 'hindi_meaning' => 'rafu karna', 'publish_date' => NULL],
            ['english_word' => 'Weave', 'pronunciation' => 'wiːv', 'hindi_word' => 'बुनना', 'hindi_meaning' => 'bunna', 'publish_date' => NULL],
            ['english_word' => 'Knit', 'pronunciation' => 'nɪt', 'hindi_word' => 'बुनना', 'hindi_meaning' => 'bunna', 'publish_date' => NULL],
            ['english_word' => 'Unravel', 'pronunciation' => 'ʌnˈrævəl', 'hindi_word' => 'सुलझाना', 'hindi_meaning' => 'suljhana', 'publish_date' => NULL],
            ['english_word' => 'Tangle', 'pronunciation' => 'ˈtæŋɡəl', 'hindi_word' => 'उलझाना', 'hindi_meaning' => 'uljhana', 'publish_date' => NULL],
            ['english_word' => 'Untangle', 'pronunciation' => 'ʌnˈtæŋɡəl', 'hindi_word' => 'सुलझाना', 'hindi_meaning' => 'suljhana', 'publish_date' => NULL],
            ['english_word' => 'Snarl', 'pronunciation' => 'snɑːl', 'hindi_word' => 'उलझना', 'hindi_meaning' => 'ulajhna', 'publish_date' => NULL],
            ['english_word' => 'Comb', 'pronunciation' => 'kəʊm', 'hindi_word' => 'कंघी करना', 'hindi_meaning' => 'kanghi karna', 'publish_date' => NULL],
            ['english_word' => 'Brush', 'pronunciation' => 'brʌʃ', 'hindi_word' => 'ब्रश करना', 'hindi_meaning' => 'brush karna', 'publish_date' => NULL],
            ['english_word' => 'Trim', 'pronunciation' => 'trɪm', 'hindi_word' => 'काटना', 'hindi_meaning' => 'katna', 'publish_date' => NULL],
            ['english_word' => 'Clip', 'pronunciation' => 'klɪp', 'hindi_word' => 'काटना', 'hindi_meaning' => 'katna', 'publish_date' => NULL],
            ['english_word' => 'Shave', 'pronunciation' => 'ʃeɪv', 'hindi_word' => 'मुंडन करना', 'hindi_meaning' => 'mundan karna', 'publish_date' => NULL],
            ['english_word' => 'Cut', 'pronunciation' => 'kʌt', 'hindi_word' => 'काटना', 'hindi_meaning' => 'katna', 'publish_date' => NULL],
            ['english_word' => 'Slice', 'pronunciation' => 'slaɪs', 'hindi_word' => 'काटना', 'hindi_meaning' => 'katna', 'publish_date' => NULL],
            ['english_word' => 'Chop', 'pronunciation' => 'tʃɒp', 'hindi_word' => 'काटना', 'hindi_meaning' => 'katna', 'publish_date' => NULL],
            ['english_word' => 'Dice', 'pronunciation' => 'daɪs', 'hindi_word' => 'टुकड़े करना', 'hindi_meaning' => 'tukde karna', 'publish_date' => NULL],
            ['english_word' => 'Grate', 'pronunciation' => 'ɡreɪt', 'hindi_word' => 'कद्दूकस करना', 'hindi_meaning' => 'kaddukas karna', 'publish_date' => NULL],
            ['english_word' => 'Peel', 'pronunciation' => 'piːl', 'hindi_word' => 'छीलना', 'hindi_meaning' => 'chhilna', 'publish_date' => NULL],
            ['english_word' => 'Core', 'pronunciation' => 'kɔːr', 'hindi_word' => 'बीज निकालना', 'hindi_meaning' => 'beej nikalna', 'publish_date' => NULL],
            ['english_word' => 'Pit', 'pronunciation' => 'pɪt', 'hindi_word' => 'गुठली निकालना', 'hindi_meaning' => 'guthli nikalna', 'publish_date' => NULL],
            ['english_word' => 'Hull', 'pronunciation' => 'hʌl', 'hindi_word' => 'छिलका उतारना', 'hindi_meaning' => 'chhilka utarna', 'publish_date' => NULL],
            ['english_word' => 'Shell', 'pronunciation' => 'ʃɛl', 'hindi_word' => 'छिलका निकालना', 'hindi_meaning' => 'chhilka nikalna', 'publish_date' => NULL],
            ['english_word' => 'Crush', 'pronunciation' => 'krʌʃ', 'hindi_word' => 'कुचलना', 'hindi_meaning' => 'kuchalna', 'publish_date' => NULL],
            ['english_word' => 'Grind', 'pronunciation' => 'ɡraɪnd', 'hindi_word' => 'पीसना', 'hindi_meaning' => 'peesna', 'publish_date' => NULL],
            ['english_word' => 'Pound', 'pronunciation' => 'paʊnd', 'hindi_word' => 'कूटना', 'hindi_meaning' => 'kootna', 'publish_date' => NULL],
            ['english_word' => 'Mash', 'pronunciation' => 'mæʃ', 'hindi_word' => 'मसलना', 'hindi_meaning' => 'masalna', 'publish_date' => NULL],
            ['english_word' => 'Puree', 'pronunciation' => 'ˈpjʊəreɪ', 'hindi_word' => 'पीसकर गाढ़ा करना', 'hindi_meaning' => 'peeskar gadha karna', 'publish_date' => NULL],
            ['english_word' => 'Blend', 'pronunciation' => 'blɛnd', 'hindi_word' => 'मिलाना', 'hindi_meaning' => 'milana', 'publish_date' => NULL],
            ['english_word' => 'Mix', 'pronunciation' => 'mɪks', 'hindi_word' => 'मिलाना', 'hindi_meaning' => 'milana', 'publish_date' => NULL],
            ['english_word' => 'Whisk', 'pronunciation' => 'wɪsk', 'hindi_word' => 'फेंटना', 'hindi_meaning' => 'phentna', 'publish_date' => NULL],
            ['english_word' => 'Beat', 'pronunciation' => 'biːt', 'hindi_word' => 'फेंटना', 'hindi_meaning' => 'phentna', 'publish_date' => NULL],
            ['english_word' => 'Knead', 'pronunciation' => 'niːd', 'hindi_word' => 'गूंधना', 'hindi_meaning' => 'gundhna', 'publish_date' => NULL],
            ['english_word' => 'Roll', 'pronunciation' => 'rəʊl', 'hindi_word' => 'बेलना', 'hindi_meaning' => 'belna', 'publish_date' => NULL],
            ['english_word' => 'Shape', 'pronunciation' => 'ʃeɪp', 'hindi_word' => 'आकार देना', 'hindi_meaning' => 'aakar dena', 'publish_date' => NULL],
            ['english_word' => 'Mold', 'pronunciation' => 'məʊld', 'hindi_word' => 'साँचे में ढालना', 'hindi_meaning' => 'sanche mein dhalna', 'publish_date' => NULL],
            ['english_word' => 'Bake', 'pronunciation' => 'beɪk', 'hindi_word' => 'सेंकना', 'hindi_meaning' => 'senkna', 'publish_date' => NULL],
            ['english_word' => 'Roast', 'pronunciation' => 'rəʊst', 'hindi_word' => 'भूनना', 'hindi_meaning' => 'bhoonna', 'publish_date' => NULL],
            ['english_word' => 'Grill', 'pronunciation' => 'ɡrɪl', 'hindi_word' => 'ग्रिल करना', 'hindi_meaning' => 'grill karna', 'publish_date' => NULL],
            ['english_word' => 'Fry', 'pronunciation' => 'fraɪ', 'hindi_word' => 'तलना', 'hindi_meaning' => 'talna', 'publish_date' => NULL],
            ['english_word' => 'Saute', 'pronunciation' => 'ˈsəʊteɪ', 'hindi_word' => 'हल्का तलना', 'hindi_meaning' => 'halka talna', 'publish_date' => NULL],
            ['english_word' => 'Boil', 'pronunciation' => 'bɔɪl', 'hindi_word' => 'उबालना', 'hindi_meaning' => 'ubalna', 'publish_date' => NULL],
            ['english_word' => 'Simmer', 'pronunciation' => 'ˈsɪmər', 'hindi_word' => 'धीरे उबालना', 'hindi_meaning' => 'dhire ubalna', 'publish_date' => NULL],
            ['english_word' => 'Steam', 'pronunciation' => 'stiːm', 'hindi_word' => 'भाप में पकाना', 'hindi_meaning' => 'bhaap mein pakana', 'publish_date' => NULL],
            ['english_word' => 'Poach', 'pronunciation' => 'pəʊtʃ', 'hindi_word' => 'हल्के पानी में पकाना', 'hindi_meaning' => 'halke pani mein pakana', 'publish_date' => NULL],
            ['english_word' => 'Broil', 'pronunciation' => 'brɔɪl', 'hindi_word' => 'ग्रिल करना', 'hindi_meaning' => 'grill karna', 'publish_date' => NULL],
            ['english_word' => 'Sear', 'pronunciation' => 'sɪər', 'hindi_word' => 'तेज आँच पर सेंकना', 'hindi_meaning' => 'tez aanch par senkna', 'publish_date' => NULL],
            ['english_word' => 'Caramelize', 'pronunciation' => 'ˈkærəməlaɪz', 'hindi_word' => 'कारमेल बनाना', 'hindi_meaning' => 'caramel banana', 'publish_date' => NULL],
            ['english_word' => 'Toast', 'pronunciation' => 'təʊst', 'hindi_word' => 'सेंकना', 'hindi_meaning' => 'senkna', 'publish_date' => NULL],
            ['english_word' => 'Burn', 'pronunciation' => 'bɜːn', 'hindi_word' => 'जलाना', 'hindi_meaning' => 'jalana', 'publish_date' => NULL],
            ['english_word' => 'Scorch', 'pronunciation' => 'skɔːtʃ', 'hindi_word' => 'झुलसाना', 'hindi_meaning' => 'jhulasana', 'publish_date' => NULL],
            ['english_word' => 'Char', 'pronunciation' => 'tʃɑːr', 'hindi_word' => 'झुलसाना', 'hindi_meaning' => 'jhulasana', 'publish_date' => NULL],
            ['english_word' => 'Cool', 'pronunciation' => 'kuːl', 'hindi_word' => 'ठंडा करना', 'hindi_meaning' => 'thanda karna', 'publish_date' => NULL],
            ['english_word' => 'Chill', 'pronunciation' => 'tʃɪl', 'hindi_word' => 'ठंडा करना', 'hindi_meaning' => 'thanda karna', 'publish_date' => NULL],
            ['english_word' => 'Freeze', 'pronunciation' => 'friːz', 'hindi_word' => 'जमाना', 'hindi_meaning' => 'jamana', 'publish_date' => NULL],
            ['english_word' => 'Thaw', 'pronunciation' => 'θɔː', 'hindi_word' => 'पिघलाना', 'hindi_meaning' => 'pighlana', 'publish_date' => NULL],
            ['english_word' => 'Preserve', 'pronunciation' => 'prɪˈzɜːv', 'hindi_word' => 'संरक्षित करना', 'hindi_meaning' => 'sanrakshit karna', 'publish_date' => NULL],
            ['english_word' => 'Ferment', 'pronunciation' => 'fəˈmɛnt', 'hindi_word' => 'किण्वन करना', 'hindi_meaning' => 'kinvan karna', 'publish_date' => NULL],
            ['english_word' => 'Pickle', 'pronunciation' => 'ˈpɪkəl', 'hindi_word' => 'अचार डालना', 'hindi_meaning' => 'achar dalna', 'publish_date' => NULL],
            ['english_word' => 'Marinate', 'pronunciation' => 'ˈmærɪneɪt', 'hindi_word' => 'अचार में डालना', 'hindi_meaning' => 'achar mein dalna', 'publish_date' => NULL],
            ['english_word' => 'Season', 'pronunciation' => 'ˈsiːzən', 'hindi_word' => 'मसाला डालना', 'hindi_meaning' => 'masala dalna', 'publish_date' => NULL],
            ['english_word' => 'Spice', 'pronunciation' => 'spaɪs', 'hindi_word' => 'मसाला डालना', 'hindi_meaning' => 'masala dalna', 'publish_date' => NULL],
            ['english_word' => 'Salt', 'pronunciation' => 'sɒlt', 'hindi_word' => 'नमक डालना', 'hindi_meaning' => 'namak dalna', 'publish_date' => NULL],
            ['english_word' => 'Sweeten', 'pronunciation' => 'ˈswiːtən', 'hindi_word' => 'मीठा करना', 'hindi_meaning' => 'meetha karna', 'publish_date' => NULL],
            ['english_word' => 'Sour', 'pronunciation' => 'ˈsaʊər', 'hindi_word' => 'खट्टा करना', 'hindi_meaning' => 'khatta karna', 'publish_date' => NULL],
            ['english_word' => 'Bitter', 'pronunciation' => 'ˈbɪtər', 'hindi_word' => 'कड़वा करना', 'hindi_meaning' => 'kadva karna', 'publish_date' => NULL],
            ['english_word' => 'Flavor', 'pronunciation' => 'ˈfleɪvər', 'hindi_word' => 'स्वाद देना', 'hindi_meaning' => 'swad dena', 'publish_date' => NULL],
            ['english_word' => 'Taste', 'pronunciation' => 'teɪst', 'hindi_word' => 'चखना', 'hindi_meaning' => 'chakhna', 'publish_date' => NULL],
            ['english_word' => 'Smell', 'pronunciation' => 'smɛl', 'hindi_word' => 'सूंघना', 'hindi_meaning' => 'sunghna', 'publish_date' => NULL],
            ['english_word' => 'Savor', 'pronunciation' => 'ˈseɪvər', 'hindi_word' => 'मजे लेना', 'hindi_meaning' => 'maze lena', 'publish_date' => NULL],
            ['english_word' => 'Devour', 'pronunciation' => 'dɪˈvaʊər', 'hindi_word' => 'खा जाना', 'hindi_meaning' => 'kha jana', 'publish_date' => NULL],
            ['english_word' => 'Nibble', 'pronunciation' => 'ˈnɪbəl', 'hindi_word' => 'कुतरना', 'hindi_meaning' => 'kutarna', 'publish_date' => NULL],
            ['english_word' => 'Bite', 'pronunciation' => 'baɪt', 'hindi_word' => 'काटना', 'hindi_meaning' => 'katna', 'publish_date' => NULL],
            ['english_word' => 'Chew', 'pronunciation' => 'tʃuː', 'hindi_word' => 'चबाना', 'hindi_meaning' => 'chabana', 'publish_date' => NULL],
            ['english_word' => 'Swallow', 'pronunciation' => 'ˈswɒləʊ', 'hindi_word' => 'निगलना', 'hindi_meaning' => 'nigalna', 'publish_date' => NULL],
            ['english_word' => 'Sip', 'pronunciation' => 'sɪp', 'hindi_word' => 'चुसकी लेना', 'hindi_meaning' => 'chuski lena', 'publish_date' => NULL],
            ['english_word' => 'Gulp', 'pronunciation' => 'ɡʌlp', 'hindi_word' => 'घूँट पीना', 'hindi_meaning' => 'ghunt peena', 'publish_date' => NULL],
            ['english_word' => 'Chug', 'pronunciation' => 'tʃʌɡ', 'hindi_word' => 'एक साँस में पीना', 'hindi_meaning' => 'ek saans mein peena', 'publish_date' => NULL],
            ['english_word' => 'Quench', 'pronunciation' => 'kwɛntʃ', 'hindi_word' => 'बुझाना', 'hindi_meaning' => 'bujhana', 'publish_date' => NULL],
            ['english_word' => 'Thirst', 'pronunciation' => 'θɜːst', 'hindi_word' => 'प्यास', 'hindi_meaning' => 'pyas', 'publish_date' => NULL],
            ['english_word' => 'Hunger', 'pronunciation' => 'ˈhʌŋɡər', 'hindi_word' => 'भूख', 'hindi_meaning' => 'bhookh', 'publish_date' => NULL],
            ['english_word' => 'Crave', 'pronunciation' => 'kreɪv', 'hindi_word' => 'लालायित होना', 'hindi_meaning' => 'lalayit hona', 'publish_date' => NULL],
            ['english_word' => 'Satisfy', 'pronunciation' => 'ˈsætɪsfaɪ', 'hindi_word' => 'तृप्त करना', 'hindi_meaning' => 'tript karna', 'publish_date' => NULL],
            ['english_word' => 'Indulge', 'pronunciation' => 'ɪnˈdʌldʒ', 'hindi_word' => 'लिप्त होना', 'hindi_meaning' => 'lipt hona', 'publish_date' => NULL],
            ['english_word' => 'Abstain', 'pronunciation' => 'əbˈsteɪn', 'hindi_word' => 'परहेज करना', 'hindi_meaning' => 'parhez karna', 'publish_date' => NULL],
            ['english_word' => 'Fast', 'pronunciation' => 'fɑːst', 'hindi_word' => 'उपवास करना', 'hindi_meaning' => 'upvas karna', 'publish_date' => NULL],
            ['english_word' => 'Feast', 'pronunciation' => 'fiːst', 'hindi_word' => 'भोज करना', 'hindi_meaning' => 'bhoj karna', 'publish_date' => NULL],
            ['english_word' => 'Dine', 'pronunciation' => 'daɪn', 'hindi_word' => 'भोजन करना', 'hindi_meaning' => 'bhojan karna', 'publish_date' => NULL],
            ['english_word' => 'Snack', 'pronunciation' => 'snæk', 'hindi_word' => 'नाश्ता करना', 'hindi_meaning' => 'nashta karna', 'publish_date' => NULL],
            ['english_word' => 'Munch', 'pronunciation' => 'mʌntʃ', 'hindi_word' => 'चबाना', 'hindi_meaning' => 'chabana', 'publish_date' => NULL],
            ['english_word' => 'Crunch', 'pronunciation' => 'krʌntʃ', 'hindi_word' => 'कुरकुराना', 'hindi_meaning' => 'kurkurana', 'publish_date' => NULL],
            ['english_word' => 'Slurp', 'pronunciation' => 'slɜːp', 'hindi_word' => 'चपचपाना', 'hindi_meaning' => 'chapchapana', 'publish_date' => NULL],
            ['english_word' => 'Burp', 'pronunciation' => 'bɜːp', 'hindi_word' => 'डकारना', 'hindi_meaning' => 'dakarana', 'publish_date' => NULL],
            ['english_word' => 'Belch', 'pronunciation' => 'bɛltʃ', 'hindi_word' => 'डकारना', 'hindi_meaning' => 'dakarana', 'publish_date' => NULL]
        ];


        foreach ($words as $word) {
            DailyWord::create($word);
        }
    }
}
