<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\DB;

class QuotesTableSeeder extends Seeder
{
    public function run()
    {
        $quotes = [
            ["A goal is a dream with a deadline.", "Napoleon Hill"],
            ["A goal properly set is halfway reached.", "Zig Ziglar"],
            ["A good conscience is a continual Christmas.", "Benjamin Franklin"],
            ["A guaranteed way to be miserable is to spend all your time trying to make everyone else happy.", "Larry Winget"],
            ["A man wrapped up in himself makes a very small bundle.", "Benjamin Franklin"],
            ["A mediocre idea that generates enthusiasm will go further than a great idea that inspires no one.", "Mary Kay Ash"],
            ["A strong foundation at home sets you up for a strong foundation at work.", "Robin Sharma"],
            ["Accept the challenges so you can feel the exhilaration of victory.", "George S. Patton"],
            ["Accept your teammates for what they are and inspire them to become all they can be.", "Robin Sharma"],
            ["Act as if what you do makes a difference. It does.", "William James"],
            ["Action is the foundational key to all success.", "Pablo Picasso"],
            ["Aim for the moon. If you miss you may hit a star.", "W. Clement Stone"],
            ["All great thinkers are initially ridiculed – and eventually revered.", "Robin Sharma"],
            ["All of your dreams await just on the other side of your fears.", "Grant Cardone"],
            ["Always choose the future over the past. What do we do now?", "Brian Tracy"],
            ["Always do your best. What you plant now, you will harvest later.", "Og Mandino"],
            ["Always give without remembering and always receive without forgetting.", "Brian Tracy"],
            ["Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", "Stephen King"],
            ["An attitude of a positive expectation is the mark of the superior personality.", "Brian Tracy"],
            ["Anger is never without a reason, but seldom with a good one.", "Benjamin Franklin"],
            ["Any fool can criticize, condemn and complain - and most fools do.", "Benjamin Franklin"],
            ["Any thought or action that you repeat over and over will eventually become a new habit.", "Brian Tracy"],
            ["Arriving at one goal is the starting point to another.", "John Dewey"],
            ["As we each express our natural genius, we all elevate our world.", "Robin Sharma"],
            ["Be gentle to all and stern with yourself.", "Saint Teresa of Avila"],
            ["Be kind whenever possible. It is always possible.", "Dalai Lama"],
            ["Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice.", "Wayne Dyer"],
            ["Become a person who would attract the results you seek.", "Jim Cathcart"],
            ["Before you begin scrambling up the ladder of success, make sure that it is leaning against the right building.", "Brian Tracy"],
            ["Being the richest man in the cemetery doesn't matter to me. Going to bed at night saying we've done something wonderful, that's what matters to me.", "Steve Jobs"],
            ["Belief triggers the power to do.", "David J. Schwartz"],
            ["Believe you can and you're halfway there.", "Theodore Roosevelt"],
            ["Big shots are only little shots who keep shooting.", "Christopher Morley"],
            ["Business is like riding a bicycle. Either you keep moving or you fall down.", "Frank Lloyd Wright"],
            ["By failing to prepare, you are preparing to fail.", "Benjamin Franklin"],
            ["Change is hardest at the beginning, messiest in the middle and best at the end.", "Robin Sharma"],
            ["Clarity precedes mastery. Craft clear and precise plans/goals/deliverables. And then block out all else.", "Robin Sharma"],
            ["Courage is not absence of fear; it is control of fear, mastery of fear.", "Mark Twain"],
            ["Crush your fears with ACTION.", "Russell Frazier"],
            ["Daily exercise is an insurance policy against future illness. The best Leaders Without Titles are the fittest.", "Robin Sharma"],
            ["Deserve your dream.", "Octavio Paz"],
            ["Discipline is the bridge between goals and accomplishment.", "Jim Rohn"],
            ["Discipline is what you must have to resist the lure of excuses.", "Brian Tracy"],
            ["Do not let what you cannot do interfere with what you can do.", "John Wooden"],
            ["Do or do not. There is no try.", "Yoda"],
            ["Do something wonderful, people may imitate it.", "Albert Schweitzer"],
            ["Do whatever you do intensely.", "Robert Henri"],
            ["Do you want to know who you are? Don't ask. Act! Action will delineate and define you.", "Thomas Jefferson"],
            ["Doing the difficult things that you’ve never done awakens the talents you never knew you had.", "Robin Sharma"],
            ["Don’t be afraid to go out on a limb. That’s where the fruit is.", "H. Jackson Brown, Jr."],
            ["Don’t settle for anything less than excellence.", "Robin Sharma"],
            ["Don't be afraid to give up the good to go for the great.", "John D. Rockefeller"],
            ["Don't fight the problem, decide it.", "George C. Marshall"],
            ["Don't give up. Don't lose hope. Don't sell out.", "Christopher Reeve"],
            ["Don't mistake movement for achievement.", "Jim Rohn"],
            ["Don't watch the clock; do what it does. Keep going.", "Sam Levenson"],
            ["Don't wish it were easier, wish you were better.", "Jim Rohn"],
            ["Dream big dreams! Imagine that you have no limitations and then decide what's right before you decide what's possible.", "Brian Tracy"],
            ["Early to bed and early to rise makes a man healthy, wealthy and wise.", "Benjamin Franklin"],
            ["Education is the beginning of transformation. Dedicate yourself to daily learning via books/audios/seminars and coaching.", "Robin Sharma"],
            ["Effective communication is 20% what you know and 80% how you feel about what you know.", "Jim Rohn"],
            ["Either I will find a way, or I will make one.", "Philip Sidney"],
            ["Either move or be moved.", "Ezra Pound"],
            ["Either write something worth reading, or do something worth writing.", "Benjamin Franklin"],
            ["Either you run the day or the day runs you.", "Jim Rohn"],
            ["Energy and persistence conquer all things.", "Benjamin Franklin"],
            ["Even if you fall on your face, you're still moving forward.", "Victor Kiam"],
            ["Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.", "Samuel Beckett"],
            ["Every choice you make has an end result.", "Zig Ziglar"],
            ["Every exit is an entry somewhere else.", "Tom Stoppard"],
            ["Every goal can be achieved if you break it down into enough small parts.", "Brian Tracy"],
            ["Every moment in front of a customer is a gorgeous opportunity to live your values.", "Robin Sharma"],
            ["Every sale has five basic obstacles: no need, no money, no hurry, no desire, no trust.", "Zig Ziglar"],
            ["Every single person in the world could be a genius at something, if they practiced it daily for at least ten years.", "Robin Sharma"],
            ["Everything you do is triggered by an emotion of either desire or fear.", "Brian Tracy"],
            ["Everything you want is on the other side of fear.", "Jack Canfield"],
            ["Everything you've ever wanted is on the other side of fear.", "George Addair"],
            ["Excellence in one area is the beginning of excellence in every area.", "Robin Sharma"],
            ["Excellence is a not a skill. It's an attitude.", "Ralph Marston"],
            ["Expect problems and eat them for breakfast.", "Alfred A. Montapert"],
            ["Failure will never overtake me if my determination to succeed is strong enough.", "Og Mandino"],
            ["Fear and self-doubt have always been the greatest enemies of human potential.", "Brian Tracy"],
            ["Fear doesn’t exist anywhere except in the mind.", "Dale Carnegie"],
            ["Fear is 100% dependent on you for its survival.", "Steve Maraboli"],
            ["Fear is the destroyer of dreams and the killer of ambitions.", "Jeffrey Benjamin"],
            ["Focus your mind on the good versus the lack.", "Robin Sharma"],
            ["For every sale you miss because you are too enthusiastic, you will miss a hundred because you are not enthusiastic enough.", "Zig Ziglar"],
            ["Freedom is not something you buy but something you earn.", "Grant Cardone"],
            ["Future intent influences and often determines present actions.", "Brian Tracy"],
            ["Give yourself something to work toward constantly.", "Mary Kay Ash"],
            ["Go out and get busy.", "Dale Carnegie"],
            ["Go the extra mile. There's no one on it!", "Grant Cardone"],
            ["Go where no one’s gone and leave a trail of excellence behind you.", "Robin Sharma"],
            ["Goals allow you to control the direction of change in your favor.", "Brian Tracy"],
            ["Goals are the fuel in the furnace of achievement.", "Brian Tracy"],
            ["Great works are performed not by strength but by perseverance.", "Samuel Johnson"],
            ["He that is good at making excuses is seldom good for anything else.", "Benjamin Franklin"],
            ["He that rises late must trot all day.", "Benjamin Franklin"],
            ["High expectations are the key to everything.", "Sam Walton"],
            ["Honesty is the best policy.", "Benjamin Franklin"],
            ["How you think when you lose determines how long it will be until you win.", "Gilbert K. Chesterton"],
            ["I attribute my success to this - I never gave or took any excuse.", "Florence Nightingale"],
            ["I don’t look to jump over 7-foot bars; I look for 1-foot bars that I can step over.", "Warren Buffet"],
            ["I never hold grudges; while you're holding a grudge, they're out dancing.", "Brian Tracy"],
            ["I want to put a ding in the universe.", "Steve Jobs"],
            ["I was motivated to be different in part because I was different.", "Donna Brazile"],
            ["I will persist until I succeed.", "Og Mandino"],
            ["I'd rather attempt to do something great and fail than to attempt to do nothing and succeed.", "Robert H. Shuller"],
            ["If it's to be, it's up me!", "Brian Tracy"],
            ["If opportunity doesn't knock, build a door.", "Milton Berle"],
            ["If passion drives you, let reason hold the reins.", "Benjamin Franklin"],
            ["If we all did the things we are capable of doing, we would literally astound ourselves.", "Thomas Edison"],
            ["If you aim at nothing, you will hit it every time.", "Tom Cochrane"],
            ["If you are not taking care of your customer, your competitor will.", "Bob Hooey"],
            ["If you are not willing to risk the usual, you will have to settle for the ordinary.", "Jim Rohn"],
            ["If you aren't going all the way, why go at all?", "Joe Namath"],
            ["If you can get yourself to read 30 minutes a day, you're going to double your income every year.", "Brian Tracy"],
            ["If you desire many things, many things will seem few.", "Benjamin Franklin"],
            ["If YOU don't believe in YOU enough to invest in YOU then don't be surprised when others don't invest in YOU.", "Grant Cardone"],
            ["If you don't see yourself as a winner, you cannot perform as a winner.", "Zig Ziglar"],
            ["If you don't set goals for yourself, you are doomed to achieve the goals of someone else.", "Brian Tracy"],
            ["If you learn from defeat you haven't really lost.", "Zig Ziglar"],
            ["If you really want to do something you'll find a way. If you don't you'll find an excuse.", "Jim Rohn"],
            ["If you want to be successful faster, you must double your rate of failure.", "Brian Tracy"],
            ["If you want to reach a goal, you must see the reaching in your own mind before you actually arrive at your goal.", "Zig Ziglar"],
            ["If you would be loved, love, and be loveable.", "Benjamin Franklin"],
            ["If you're going through hell, keep going.", "Winston Churchill"],
            ["If you're offered a seat of a rocket ship, don't ask what seat! Just get on.", "Sheryl Sandberg"],
            ["In business, it's better to mean a lot to a few rather than a little to many.", "Larry Winget"],
            ["Innovation distinguishes between a leader and a follower.", "Steve Jobs"],
            ["Integrity is what we do, what we say and what we say we do.", "Don Galer"],
            ["Investing energy & resources in yesterday prevents you from creating the future you deserve.", "Grant Cardone"],
            ["Investment in knowledge pays the best interest.", "Benjamin Franklin"],
            ["It ain't over till' it's over.", "Yogi Berra"],
            ["It doesn't matter where you are coming from. All that matters is where you are going.", "Brian Tracy"],
            ["It generally takes about 10 years to become an overnight sensation.", "Robin Sharma"],
            ["It is impossible to succeed without failing.", "Brian Tracy"],
            ["It is not necessary to do extraordinary things to get extraordinary results.", "Warren Buffet"],
            ["It is the working man who is the happy man. It is the idle man who is the miserable man.", "Benjamin Franklin"],
            ["It takes guts to work hard enough to get the things you want.", "Cole Bayer"],
            ["It takes many good deeds to build a good reputation, and only one bad one to lose it.", "Benjamin Franklin"],
            ["It takes more than good intentions to get something done.", "Larry Winget"],
            ["It's easier to prevent bad habits than to break them.", "Benjamin Franklin"],
            ["It's hard to fail, but it is worse never to have tried to succeed.", "Theodore Roosevelt"],
            ["It's not about having the right opportunities, it's about handling the opportunities right.", "Mark Hunter"],
            ["It's not failure itself that holds people back; it is the fear of failure that paralyzes you.", "Brian Tracy"],
            ["Keep your eyes on the stars and your feet on the ground.", "Theodore Roosevelt"],
            ["Knowing what to do and not doing it is the same as not knowing what to do.", "Robin Sharma"],
            ["Lack of direction, not lack of time, is the problem. We all have a twenty-four hour day.", "Zig Ziglar"],
            ["Leaders think and talk about the solutions. Followers think and talk about the problems.", "Brian Tracy"],
            ["Leadership is doing what is right when no one is watching.", "George Van Valkenburg"],
            ["Leadership is the ability to elicit extraordinary performance from ordinary people.", "Brian Tracy"],
            ["Lean in, speak out, have a voice in your organization, and never use the word 'sorry'.", "Trish Bertuzzi"],
            ["Leap, and the net will appear.", "John Burroughs"],
            ["Look for the good in every person in every situation. You'll almost always find it.", "Brian Tracy"],
            ["Lost time is never found again.", "Benjamin Franklin"],
            ["Love me or hate me, at least now you know me.", "Grant Cardone"],
            ["Lucky is where skill meets persistence.", "Robin Sharma"],
            ["Make a customer not a sale.", "Katherine Barchetti"],
            ["Make the work you are doing today better than the work you did yesterday.", "Robin Sharma"],
            ["Make your life matter.", "Robin Sharma"],
            ["Measure your success by your inner scorecard versus an outer one.", "Robin Sharma"],
            ["Money and success demand attention. Ignore either and you will have neither.", "Grant Cardone"],
            ["Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all.", "Dale Carnegie"],
            ["Most people think selling is the same as talking. But the most effective salespeople know that listening is the most important part of their job.", "Roy Bartell"],
            ["Motivation is the art of getting people to do what you want them to do because they want to do it.", "Dwight D. Eisenhower"],
            ["Motivation is what gets you started. Habit is what keeps you going.", "Jim Rohn"],
            ["Motivation will almost always beat mere talent.", "Norman Ralph Augustine"],
            ["My dear friend, clear your mind of can't.", "Samuel Johnson"],
            ["Never confuse motion with action.", "Benjamin Franklin"],
            ["Never leave that till tomorrow which you can do today.", "Benjamin Franklin"],
            ["Never leave the site of a strong idea without doing something to execute around it.", "Robin Sharma"],
            ["Never miss a moment to celebrate another.", "Robin Sharma"],
            ["Never miss a moment to encourage someone you work with.", "Robin Sharma"],
            ["Never say anything about yourself you do not want to come true.", "Brian Tracy"],
            ["Never, never, never give up.", "Winston Churchill"],
            ["No bird soars too high if he soars with his own wings.", "William Blake"],
            ["No matter what the level of your ability, you have more potential than you can ever develop in a lifetime.", "James T. McCay"],
            ["No one can make you feel inferior without your consent.", "Eleanor Roosevelt"],
            ["Nobody cares how much you know, until they know how much you care.", "Theodore Roosevelt"],
            ["Nobody counts the number of ads you run; they just remember the impression you make.", "William Bernbach"],
            ["Nobody works better under pressure. They just work faster.", "Brian Tracy"],
            ["Nothing about an excuse can help your situation.", "Grant Cardone"],
            ["Nothing fails like success. Because when you are at the top, it’s so easy to stop doing the very things that brought you to the top.", "Robin Sharma"],
            ["Nothing is impossible; the word itself says 'I'm possible'", "Audrey Hepburn"],
            ["On any given Monday I am one sale closer and one idea away from being a millionaire.", "Larry D. Turner"],
            ["One finds limits by pushing them.", "Herbert Simon"],
            ["One of the primary tactics for enduring winning is daily learning.", "Robin Sharma"],
            ["One of the very worst uses of time is to do something very well that need not be done at all.", "Brian Tracy"],
            ["One way to keep momentum going is to have constantly greater goals.", "Michael Korda"],
            ["Only I can change my life. No one can do it for me.", "Carol Burnett"],
            ["Opportunities are usually disguised as hard work, so most people don't recognize them.", "Ann Landers"],
            ["Opportunity doesn't knock, it presents itself when you beat down the door.", "Kyle Chandler"],
            ["Optimism is the one quality associated with success and happiness than any other.", "Brian Tracy"],
            ["Other people’s opinions of you are none of your business.", "Robin Sharma"],
            ["Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", "Thomas Edison"],
            ["Outstanding people have one thing in common: An absolute sense of mission.", "Zig Ziglar"],
            ["Passion + production = performance.", "Robin Sharma"],
            ["Patience is a key element of success.", "Bill Gates"],
            ["Peak performers replace depletion with inspiration on a daily basis.", "Robin Sharma"],
        ];

        DB::setDefaultConnection('school');
        Config::set('database.connections.school.database', 'eschool_saas_5_asif');
        DB::purge('school');
        DB::connection('school')->reconnect();
        DB::setDefaultConnection('school');

        foreach ($quotes as $quote) {
            DB::table('quotes')->insert([
                'quote' => $quote[0],
                'author' => $quote[1],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
// * * * * * cd /path-to-your-laravel-project && php artisan schedule:run >> /dev/null 2>&1
