name: Deploy-to-EC2-Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-52-66-89-121.ap-south-1.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/hrskadmin"
